runtime: nodejs
env: flex
service: abbott-platform-info-botapp

manual_scaling:
  instances: 1

env_variables:
  appName: 'abbott-platform-info-botapp'
  botFriendlyName: 'Abbott Platform'
  enable_abbott_engine: true
  defaultSettings: '{ "adminUserId": "0", "setupCompleted": true }'
  ABBOTT_LOG_LEVEL: 'error'
  ABBOTT_HOSTADDRESS: 'https://abbott-platform-info-botapp-dot-ciandt-cognitive-sandbox.appspot.com'
  NLP_APIAI_TOKEN: %NLP_APIAI_TOKEN%

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?\..*$
- ^(.*/)?\.bak$
- \.tmp/.*
- \.data/.*
- \.vscode/.*
- ^k8s/.*
- ^Dockerfile$
- ^docker[-].*$
- ^.*\.sh$
- ^apiai_bkp/.*
